### ISSUE TITLE
Incompatibility with johnbillion/query-monitor on PHP errors handling

### ISSUE THREAD

**Issue by pierre-dargham** [inpsyde/Wonolog#22]
Hello,

I've been playing with wonolog, that I may want to include as an embed component in the future releases of [our custom WP stack](https://github.com/globalis-ms/wp-cubi)

So far, I'm impressed with the quality of the documentation that is very complete for a first public release, and the code / functionalities seem to match their purpose, well done here !

However, I have noticed that, when used in a WP install with plugin [johnbillion/query-monitor](https://github.com/johnbillion/query-monitor) activated, PHP errors are no longer caught and logged by wonolog.

This is pretty logical, because wonolog and query-monitor both override php error handler and shutdown function, and because query-monitor is loaded after wonolog, wonolog doesn't have control anymore on php errors.

Do you have already thought about this incompatibility ? Do you have an idea on how we should deal with it ? My purpose here would be to find a way of having both handlers functionalities working at the same time.

I've submit [a PR on query-monitor](https://github.com/johnbillion/query-monitor/pull/258) that should be merged in the next release, and will allow us to disable / override the PHP error controller of the plugin.

After that, how can we make both functionnalities work ?

1. Disable query-monitor PHP errors collector and hook on `\Inpsyde\Wonolog\LOG` to send data to query-monitor ?

2. Extends wonolog `PhpErrorController` with a class that handles both functionalities, registering it as both wonolog controller and query-monitor collector ?

3. Something better ?

Bests regards,
Pierre

**Comment by gmazzap** [comment]
Hi @pierre-dargham, thanks for reporting the issue, and with such details.

The fact that both Wonolog and Query Monitor register a shutdown function is not an issue, if fact all the shutdown functions are executed in order of registration.

Sadly, the same can't be said for error handlers, the one called later, override the previous.

Thanks to shutdown functions there could be a quite easy solution for you.

Assuming PHP error handling in Wonolog enabled as as usual, you could register a shutdown function, that listen for errors on shutdown. Considering that all registered shutdown functions are ran, you can use `error_get_last()` to get last error an manually call `PhpErrorController::on_error()`.

Something like this:

```php
register_shutdown_function(function() {
	
	// nothing to do if QueryMonitor is not there
	if (! class_exists(\QueryMonitor::class)) {
		return;
	}
	
	$err = error_get_last();
		
	static $fatals;
	$fatals or $fatals = [
		E_ERROR,
		E_PARSE,
		E_CORE_ERROR,
		E_CORE_WARNING,
		E_COMPILE_ERROR,
		E_COMPILE_WARNING,
	];
		
	// nothing to do if no error or the error is fatal
	if ( ! $err || in_array( $error[ 'type' ], $fatals, TRUE )) {
		return;
	}
		
	$wonolog_error_controller = new Inpsyde\Wonolog\PhpErrorController();
	$wonolog_error_controller->on_error(...array_values($err));	
} );
```

This could easily go in the MU plugin that bootstraps Wonolog, so that if no Wonolog is there, nothing of that will be done.

Note that in the snippet above nothing is done for fatal errors, because `PhpErrorController` _already_ listen for fatals on shutdown (see https://github.com/inpsyde/Wonolog/blob/master/src/PhpErrorController.php#L119-L143), so no need to duplicate those logs.

This should work, but this assumes that QueryMonitor is called _after_ Wonolog. If you use a MU plugin to bootsrap Wonolog, as suggested in the docs, that is true, so no issue.

To make this solveable in a more general way, without assumptions on the whole system, we would need to collaborate to with @johnbillion, for example he could pass the error data to the filter `'qm/collect/php_errors_return_value'` so that listening that filter would be possible to call `PhpErrorController::on_error()` with error data passed by the filter. (Unfortunately, `error_get_last()` does not work from _inside_ the error handler, so if the filter doesn't pass error data, only way to get them is to use a  shutdown handler as shown in the snippet above.)

**Comment by gmazzap** [comment]
In 61c286c I did what I'm asking @johnbillion to do in his plugin. After someone else review, this could be merged.

**Comment by johnbillion** [comment]
Thanks for the ping. I'll take a look next week.

**Comment by pierre-dargham** [comment]
Hello @gmazzap and thank you for the detailed answer :+1: 
I'll test the first solution you proposed, and come back to you

**Comment by tfrommen** [comment]
I would like to propose another way than what @gmazzap illustrated in https://github.com/inpsyde/Wonolog/issues/22#issuecomment-312435807 to ensure errors are logged by Wonolog.

Rather than making people write something like the above snippet, in all of their projects that are using both Wonolog and Query Monitor (or any other error-handler-manipulating party, for that matter), and also tailor it to QueryMonitor (see the `QueryMonitor::class` reference), I would extend Wonolog's built-in `PhpErrorHandler` in the following way:

* register a new shutdown handler;
* inside that handler, check the current error handler;
* if it's Wonolog's, bail;
* if it's something else, manually log the error (by passing it on to the `on_error` method).

I [implemented](https://github.com/inpsyde/Wonolog/commit/e2e67e470391cace225305783c96ab3c1b664de5) that in [a dedicated branch for review](https://github.com/inpsyde/Wonolog/compare/ensure_error_handling).

I kept the similar `on_fatal()` method still separate, because I like the separation, and also the (conditional) logic of a method that combines both cases would be too complex, in my opinion.
However, I moved the (not even static) fatals map from `on_fatal()` to a static field that is referenced from within both methods.

Comments?

**Comment by pierre-dargham** [comment]
Hello @tfrommen,

I just checked out your commit. I think there is at least 2 problems with your solution :

1. query-monitor restores previous php error handler on `shutdown` hook (see `tear_down` method at https://github.com/johnbillion/query-monitor/blob/master/collectors/php_errors.php#L179:L183) so your code will always bail on https://github.com/inpsyde/Wonolog/compare/ensure_error_handling#diff-053f89d6dfddc8578b598012abf4b702R110 and nothing will be logged.

2. Even if we don't bail here, we'll only get the last error with https://github.com/inpsyde/Wonolog/compare/ensure_error_handling#diff-053f89d6dfddc8578b598012abf4b702R114, so if we have 10 warnings and notices, only the last one will we logged. It could be very misleading when reading the logs / debugging an application.

I think we have a limit on PHP language here, that won't allow us to have a generic solution. Because only the last function registered with `set_error_handler()` is executed, and because `error_get_last()` only returns the last error, we won't be able to catch all errors if Wonolog handler has been overridden, unless we have a specific compatibility code that calls Wonolog `òn_error()` method from the last php error handler function.

To achieve our goal here, I think the road-map should be :

1. Add an action `qm/collect/new_php_error` in query-monitor `error_handler` method, that forwards all the error data (or modify existing filter `qm/collect/php_errors_return_value` as suggested by @gmazzap)
2. Provide a way to access Wonolog `PhpErrorController` instance from the outside
3. Provide a separate package or mu-plugin that implements wonolog and query-monitor compatibility layer, by hooking Wonolog `on_error` method on query-monitor `error_handler` action/filter

Steps 2. and 3. could be replaced with 'Directly hook on query-monitor `qm/collect/new_php_error` action from Wonolog `PhpErrorController`, but you may not want to introduce specific compatibility code into Wonolog core.

Comments ?

Maybe @johnbillion had the time to take a look ?

Bests regards,
Pierre

**Comment by tfrommen** [comment]
Hello @pierre-dargham - yes, you are absolutely right.
We discussed this already internally, but I forgot to comment on this here.

**Comment by pierre-dargham** [comment]
Ok :+1: 

I just opened a PR corresponding to step 1. on query-monitor https://github.com/johnbillion/query-monitor/pull/263

Could you make something for step 2. ?

After that, step 3 will be easy : we'll just have something like `add_action('qm/collect/new_php_error', array( $wonolog_phperrorcontroller, 'on_error'), 10, 5);`. Only question regarding this step will be how and where to wrap this.

Bests regards,
Pierre

**Comment by pierre-dargham** [comment]
Hello there,

The PR we needed on query-monitor has been merged in last release https://github.com/johnbillion/query-monitor/blob/2.14.0/collectors/php_errors.php#L56 and it makes step 1. complete.

Anything new on step 2. ? (we need to access Wonolog `PhpErrorController` instance from the outside so we can reference Wonolog `on_error` method)

Bests regards,
Pierre

**Comment by gmazzap** [comment]
Hi @pierre-dargham and thanks for your collaboration.

`PhpErrorController` is a stateless object, without dependencies, so it is _newable_: you don't need to access the instance Wonolog uses, but you can create another instance without side effects.

```php
add_action(
    'qm/collect/new_php_error',
    [ new Inpsyde\Wonolog\PhpErrorController(), 'on_error' ],
    10,
    5
);
```

**Comment by pierre-dargham** [comment]
You're right @gmazzap . If we're sure that `PhpErrorController` will remain a stateless object in future releases, the issue is solved :+1: 

I close the thread. Maybe a mention of this incompatibility / solution in the documentation (or in the FAQ, or elsewhere) would be a good thing.

Also, thank you @johnbillion for merging the new hooks on qm.

Bests regards,
Pierre
