### ISSUE TITLE
Disable specific listener within a Channel

### ISSUE THREAD

**Issue by Mallinanga** [inpsyde/Wonolog#28]
Awesome package guys!

I just wanted to ask if there is a way to disable a specific listener/action within a Channel, but not the whole Channel.

For example if I wanted to disable just the login failed check within the Security channel, how would I do that?

Is there a filter that lists all available actions within a channel where I can unset some of them?

**Comment by gmazzap** [comment]
Hi @Mallinanga 

Th WP hooks that Wonolog listens to are not defined by channel, but by "Listeners".

Please have a look at ["Customizing Default Hook Listeners" chapter of docs](https://inpsyde.github.io/Wonolog/docs/05-wonolog-customization.html#customizing-default-hook-listeners) to see all the listeners that Wonolog uses by default.

Each listeners listen to a one or a few hooks. If you want to see the code involved, all listeners are in this folder: https://github.com/inpsyde/Wonolog/tree/master/src/HookListener.

For example, the "login failed" logging is done by the [`FailedLoginListener`](https://github.com/inpsyde/Wonolog/blob/master/src/HookListener/FailedLoginListener.php).

As shown in the documentation linked above, you can tell Wonolog which listeners to use.

For example with a bootstrap like this:

```php
/*
 * Plugin Name: Wonolog Configuration MU plugin.
 */
use Inpsyde\Wonolog;

if ( ! defined( 'Inpsyde\Wonolog\LOG' ) ) {
    return;
}

Wonolog\bootstrap( null, Wonolog\LOG_PHP_ERRORS|Wonolog\USE_DEFAULT_PROCESSOR )
    ->use_hook_listener( new HookListener\CronDebugListener() )
    ->use_hook_listener( new HookListener\DbErrorListener() )
    ->use_hook_listener( new HookListener\HttpApiListener() )
    ->use_hook_listener( new HookListener\MailerListener() )
    ->use_hook_listener( new HookListener\QueryErrorsListener() )
    ->use_hook_listener( new HookListener\WpDieHandlerListener() );
```

Here you can see how when bootstrapping Wonolog, you can cherry-pick the listeners you want to use (and possibly configuring them by passing arguments to their constructors), so you can just avoid to use the `FailedLoginListener` as I did in the snippet above.

An alternive way is to use the `'wonolog.hook-listener-enabled'` filter hook.

For example:

```php
/*
 * Plugin Name: Wonolog Configuration MU plugin.
 */
use Inpsyde\Wonolog\HookListener;

if ( ! defined( 'Inpsyde\Wonolog\LOG' ) ) {
    return;
}

add_filter(
    'wonolog.hook-listener-enabled',
    function( $enabled, HookListener\HookListenerInterface $listener ) {
         return $listener instanceof HookListener\FailedLoginListener ? false : $enabled;
    },
    10,
    2
);

Inpsyde\Wonolog\bootstrap();
```

Both ways produces the same result: the failed login listener will not be used. In first case it is not bootstrapped at all, in the second case it's "blacklisted" via a filter.

Honestly I prefer the first approach, because you need to call `bootstrap()` anyway, and you don't create any object you are not going to use (even if creation is not expensive at all), but using the second approach it would be easy to use some logic so disabling listeners based on some conditions.
