### ISSUE TITLE
Coding standards: rename wonolog.log to wonolog_log

### ISSUE THREAD

**Issue by bashaus** [inpsyde/Wonolog#29]
```
FILE: [...]/wp-content/plugins/[...]/[...].php
--------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------
 34 | WARNING | Words in hook names should be separated using underscores.
    |         | Expected:  'wonolog_log', but found:  'wonolog.log'.
--------------------------------------------------------------------------------
```

When running PHPCS, using the WordPress-Extra standards, I receive the error message.

Would like to have an open discussion about this but can we setup wonolog_log as the main hook and wonolog.log as an alias for backwards compatibility?

**Comment by Chrico** [comment]
Howdy @bashaus .

How do you integrate Wonolog into your Plugin/System? In theory you should avoid to run PHPCS on `vendor/`-Folder or packages you load externally.

In general: No, because we not only have `wonolog.log` as hook named with that convention. :-)

**Comment by bashaus** [comment]
Hi @Chrico 

I am currently excluding third-party plugins and the composer vendor directory from my project. Regardless of whether this is in a plugin I've written myself, even if I was to put it in my `wp-config.php` file, I am still going to have this error returned by phpcs.

**Comment by gmazzap** [comment]
@bashaus We at Inpsyde don't follow WPCS. For many different reasons.

So, no, we don't want to change the main (nor other) hooks according to WPCS.

I understand it could be a problem if in your plugins you do:

```php
do_action( 'wonolog.log', ... );
```

and I understand that ignoring via comments like:

```php
do_action( 'wonolog.log', ... ); // phpcs:ignore
```

could be annoying if you have a lot of these calls.

So the issue is legit, but has different solutions that do not involve us to change our coding styles.

## Solution 1: Custom Hook Listeners

The main way we would like people to extend Wonolog, is to use [Custom Hook Listeners](https://inpsyde.github.io/Wonolog/docs/06-custom-hook-listeners.html).

If you use this way to integrate with Wonolog, you'll never need to call `'wonolog.log'`.

## Solution 2: Use the `LOG` constant

`"wonolog.log"` hook name is stored in a [custom constant](https://github.com/inpsyde/Wonolog/blob/master/inc/bootstrap.php#L23) you can leverage in plugins integrating with Wonolog.

```
do_action( Inpsyde\Wonolog\LOG, ... );
```

Here I'm assuming that the plugin knows already Wonolog is available, so the constant is defined. If not, you have to check for that.

You could also have a wrapping function like:

```
function my_plugin_log( $message ) {
   if ( defined( 'Inpsyde\Wonolog\LOG' ) ) {
       do_action( Inpsyde\Wonolog\LOG, $message);
       return;
   }
   // Wonolog is not there, use alternative logging method
   error_log( $message );
}
```

## Solution 3: Instruct WPCS to accept dots as word separator

If you are writing a plugin that integrates with Wonolog could make sense to instruct WPCS that you are going to use dots as possible word separator for hooks.

In a `phpcs.xml` file, that is as easy as adding:

```xml
<rule ref="WordPress.NamingConventions.ValidHookName">
    <properties>
        <property name="additionalWordDelimiters" value="."/>
    </properties>
</rule>
```
