### ISSUE TITLE
Upgrade to Monolog 2*

### ISSUE THREAD

**Issue by anthonylpdev** [inpsyde/Wonolog#48]
Have you scheduled to upgrade Wonolog to be compatible with latest Monolog version (2.0 at least) ?
Thanks =)

**Comment by Chrico** [comment]
Howdy!

We're going to plan support for Monolog 2.x and Psr-3 in our next 2.x version of Wonolog. :-)

**Comment by noplanman** [comment]
@Chrico Any progress on the Wonolog v2 front regarding Monolog 2.*?

**Comment by BrandonOldenhof** [comment]
@Chrico Are there any updates on this? I noticed that there hasn't been any activity on the [RFC PR that was made last September](https://github.com/inpsyde/Wonolog/pull/55).
Meanwhile, I can't implement Wonolog because our root installation requires monolog/monolog:2.3 😞

**Comment by gmazzap** [comment]
Not have an ETA yet, but that is going to happen _soonish_.

Actually, you can already try out the [`2.x` branch](https://github.com/inpsyde/Wonolog/tree/2.x) which is using Monolog 2.3.5+ and _should be_ fully functional.

**Comment by benoitchantre** [comment]
Is this project still maintained? If yes, do you have any idea when a new release should happen?

**Comment by gmazzap** [comment]
Hi @benoitchantre the project is mainatined, and we have in use in _many_ production sites, os it is very unlikely it will die.

The issue is that those many websites we have are all using version 1, and for several reason is not easy to update to v2.

Without the possibility to test it in real world, we haven't released a version which is supposed to be "stable".

If you have time&will to test v2, the branch [2.x](https://github.com/inpsyde/Wonolog/tree/2.x) is there, ready for being tested. I might even release a `2.0.0-beta`, not sure it changes much from just using the branch.

**Comment by benoitchantre** [comment]
Hi @gmazzap, thank you for your feedback. For now, I have no project using this package in production. I'm testing it.
I'll then upgrade to v2 and test it.

**Comment by timnolte** [comment]
We are looking for a solution to begin shipping WordPress logs to other services in a standard way. I was considering bringing up to our development team that if this project is no longer maintained we could fork it and maintain our own version of it. I'm glad to hear that there is at least some sentiment that it is still under active maintenance. I will also look at installing the 2.x branch and do some testing.

**Comment by gmazzap** [comment]
[v2 first beta](https://github.com/inpsyde/Wonolog/releases/tag/2.0.0-beta.1) just released.
It will be stable soon.
The documentaion is also [updated in the 2.x branch](https://github.com/inpsyde/Wonolog/tree/2.x/docs).
If you have feedback to share, please do so. Thanks.
