### ISSUE TITLE
Version 1 already uses PHP 7 code

### ISSUE THREAD

**Issue by dnaber-de** [inpsyde/Wonolog#59]
While review the RFC for version 2 I noticed that `LogActionSubscriber` already uses `\Throwable` which was introduced at PHP 7 but Wonolog states to be compatible with 5.6.

The fact that this wasn't discovered until now leads me to the assumption that PHP 5.6 isn't used any more together with Wonolog. I just leave that here as «known Issue» for the sake of completeness. If we decide to fix it we should look throughout the code base to make sure it is actually compatible with 5.6

**Comment by gmazzap** [comment]
@dnaber-de That is not a problem.

Having duplicate `catch` block for `Throwable` and `Exception` is a standard practice for code that supports _both_ PHP 5 and PHP 7.

PHP 7 will stop at the first branch, PHP 5 will stop ad the second. Consider that since PHP 5.1 does not check the existence of the class/interface that is used in `catch`.

See https://3v4l.org/0fBUo

The reason to use `Throwable` is to be able to catch errors that in PHP 5 were warnings/fatal errors and become `Error` in PHP 7.

**Comment by dnaber-de** [comment]
I see.
